global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-cliente'

    static_configs:
      - targets: ['localhost:9090','localhost:8081']
        labels:
          application: 'api-cliente'

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8081']